### ISSUE TITLE
Question - Current/voltage sensitivity similar to INA219

### ISSUE THREAD

**Issue by ear9mrn** [beast-devices/Arduino-INA3221#1]
Thanks for sharing your code. With the single channel version of this board (INA219) it is possible to adjust the max voltage/amp that is measure to increase the sensitivity of the measurements. Is the same thing possible with this version, I looked through your code but did not see anything obvious (although I am no expert at this)?

Thanks,

Pete.

**Comment by abondarevs** [comment]
Hi Pete,

Unfortunately INA3221 doesn't support dynamic range. It is fixed –163.84 to 163.8 mV for the current sense.

I can recommend you to look at [PAC1934](https://www.microchip.com/wwwproducts/en/PAC1934). It has four channels, has energy accumulator, voltage range up to 32V, higher ADC resolution and costs less. It has a bit worse voltage offset and gain error though.

**Comment by ahillbom** [comment]
> Thanks for sharing your code. With the single channel version of this board (INA219) it is possible to adjust the max voltage/amp that is measure to increase the sensitivity of the measurements. Is the same thing possible with this version, I looked through your code but did not see anything obvious (although I am no expert at this)?
> 
> Thanks,
> 
> Pete.

Hi Pete,

Unfortunately INA3221 doesn't support dynamic range. It is fixed –163.84 to 163.8 mV for the current sense.

I can recommend you to look at [PAC1934](https://www.microchip.com/wwwproducts/en/PAC1934). It has four channels, has energy accumulator, voltage range up to 32V, higher ADC resolution and costs less. It has a bit worse voltage offset and gain error though.
