### ISSUE TITLE
Issue with negative current (or current flows from VIN- to VIN+)

### ISSUE THREAD

**Issue by yetoo** [beast-devices/Arduino-INA3221#2]
Hi Andrejs, first, thank you for sharing. About the issue, I tried your code with this setup : 
3.3 >> CH1VIN+
CH1VIN- >> Res 100ohm
Res 100ohm >> GND
It works fine, I get ~ 0.029 A

But once I flip this setup as follow :
3.3 >> CH1VIN-
CH1VIN+ >> Res 100ohm
Res 100ohm >> GND
I get a weird value of 42949.645, do you have any explanation for that? 

Thank you for your time.

**Comment by ahillbom** [comment]
Hi! Thank you for reporting the issue. Can you please provide the excerpt of your code? Also, which MCU are you using?

**Comment by yetoo** [comment]
Sorry for the late to answer. I will provide you a full video on how it
happened.

Sorry again.

**Comment by ahillbom** [comment]
No worries! My answer was way later.

The issue is fixed in https://github.com/beast-devices/Arduino-INA3221/commit/be202dca720899e1535c159ffee7e077071eb1b1

**Comment by yetoo** [comment]
Thank you very much

Le lun. 5 avr. 2021 à 13:56, Andrejs Bondarevs ***@***.***> a
écrit :
